#page title
page_title                                :                                           # Automatically populates with app name if not set and if android app ID is set. Otherwise enter manually.

# App Info
android_app_id                            : com.ir.irise_app                          # Required. Enter android app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.ir.irise_app                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.webp                        # Automatically populates if not set and if android app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Refresh(Early Access)                     # Automatically populates if not set and if android app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if android app ID is set.  Otherwise enter manually.
app_description                           : An education resources and information guide for Saskatoon residents

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Aholagunju                                
your_link                                 : https://mobile.twitter.com/aholagunju                     
your_city                                 : Saskatchewan                                
email_address                             : info@trulyalivefoundation.org
facebook_username                         : Truly-Alive-Youth-and-Family-Foundation-Inc-893782087407356/                                          
instagram_username                        : trulyalivefoundation/
twitter_username                          : tayffi 
linkedin_username                         : company/truly-alive-foundation 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : FINANCIAL RESOURCES 
    description                           : <p>-Budgeting & Debt</p>
                                            <p>-Government Intervantion</p>
                                            <p>-City of Saskatoon intervention</p>
                                            <p>-Financial Fruad Activity</p>
    fontawesome_icon_name                 : magic
    
  - title                                 : HEALTH RESOURCES
    description                           : <p>-Covid 19 general & Prevention</p>
                                            <p>-Covid 19 Assessment</p>
                                            <p>-Mental Health</p>
                                            <p>-Family & Children</p>
    fontawesome_icon_name                 : mobile

  - title                                 : SOCIO RESOURCES
    description                           : <p>-Re-opening plan(s)</p>
                                            <p>-Travel</p>
                                            <p>-Education & Students</p>
                                            <p>-Immigration & Employment</p>
                                            <p>-Prejudice & Stigma</p>
    fontawesome_icon_name                 : play-circle

  - title                                 : FAMILY RESOURCES
    description                           : 
    fontawesome_icon_name                 : sync

  - title                                 : COMMUNITY SERVICES RESOURCES
    description                           : <p>-Cultural Association<p>
                                            <p>-Health & Well Being</p>
                                            <p>-Grocery Stores</p>
                                            <p>-Community Supports</p>
    fontawesome_icon_name                 : adjust
  
  - title                                 : COVID 19 RESOURCES
    description                           : <p>-COVID 19 Advice for the public</p>
                                            <p>-Getting your Workplace Ready</p>
                                            <p>-COVID 19 and Indigenous</p>
    fontawesome_icon_name                 : star

  



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
